import { expect, test } from '@playwright/test'

const seed = '/preview.html?fresh=0&at=/c/c1/chat/seed1'

test('desktop document spans most of the workspace under the composer and fullscreen restores it', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto(seed)
  await expect(page.locator('body')).not.toContainText('not retrieved')
  await page.getByRole('button', { name: 'Open Week 03 — Aug 17-21, 2026', exact: true }).click()
  const panel = page.locator('.is-composer-overlay')
  const composer = page.locator('#composer-input')
  await expect(panel).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.panel-scrim')).toHaveCount(0)
  await expect(panel.locator('.plan-table')).toBeVisible()
  await page.waitForTimeout(260)
  await composer.fill('Keep the lesson plan open while I type.')
  await expect(composer).toBeFocused()
  const assertComposerOverlay = async () => {
    const inputBox = await composer.boundingBox()
    const panelBox = await panel.boundingBox()
    const workspaceBox = await page.locator('.workspace-panes').boundingBox()
    const leftRailBox = await page.locator('.app-rail').boundingBox()
    const actionBox = await panel.locator('.doc-head > div:last-child').boundingBox()
    expect(panelBox.x).toBeGreaterThanOrEqual(leftRailBox.x + leftRailBox.width - 2)
    expect(panelBox.width).toBeGreaterThan(workspaceBox.width * 0.7)
    expect(actionBox.x + actionBox.width).toBeLessThanOrEqual(panelBox.x + panelBox.width)
    const tableScroll = panel.locator('.plan-table-scroll')
    if (await tableScroll.count()) {
      expect(await tableScroll.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    }
    expect(inputBox.x + inputBox.width).toBeGreaterThan(panelBox.x)
    const composerIsOnTop = await composer.evaluate((el) => {
      const rect = el.getBoundingClientRect()
      return document.elementFromPoint(rect.right - 8, rect.y + rect.height / 2) === el
    })
    expect(composerIsOnTop).toBe(true)
  }
  await assertComposerOverlay()
  const body = panel.locator('.doc-body')
  await composer.fill('Keep the lesson plan open while I type.\nSecond line\nThird line\nFourth line\nFifth line\nSixth line')
  await body.evaluate((el) => { el.scrollTop = el.scrollHeight })
  const sheetBox = await body.locator('.doc-sheet').boundingBox()
  const composerBox = await page.locator('.composer-shell').boundingBox()
  expect(await body.evaluate((el) => parseFloat(getComputedStyle(el).paddingBottom))).toBeGreaterThan(composerBox.height)
  expect(sheetBox.y + sheetBox.height).toBeLessThanOrEqual(composerBox.y)
  await composer.fill('Keep the lesson plan open while I type.')
  await panel.getByRole('button', { name: 'Enter fullscreen' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.is-overlay-fullscreen')).toBeVisible()
  await expect(page.locator('.plan-table')).toBeVisible()
  await expect(composer).toBeVisible()
  await expect(composer).toHaveValue('Keep the lesson plan open while I type.')
  const fullscreenComposerBox = await composer.boundingBox()
  const fullscreenPanelBox = await page.locator('.is-overlay-fullscreen').boundingBox()
  expect(fullscreenComposerBox.y).toBeGreaterThan(fullscreenPanelBox.y)
  expect(fullscreenComposerBox.y + fullscreenComposerBox.height).toBeLessThanOrEqual(fullscreenPanelBox.y + fullscreenPanelBox.height)
  const fullscreenComposerIsOnTop = await composer.evaluate((el) => {
    const rect = el.getBoundingClientRect()
    return document.elementFromPoint(rect.right - 8, rect.y + rect.height / 2) === el
  })
  expect(fullscreenComposerIsOnTop).toBe(true)
  await page.getByRole('button', { name: 'Exit fullscreen' }).click()
  await expect(panel).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(composer).toHaveValue('Keep the lesson plan open while I type.')
  await panel.getByRole('button', { name: 'Close document' }).click()
  await expect(panel).toHaveCount(0)
  await page.getByRole('button', { name: /Week 03 Quiz — Voice & Tone Quiz/ }).click()
  await expect(panel).toBeVisible()
  await composer.fill('Quiz and chat remain independent.')
  await expect(composer).toBeFocused()
  await assertComposerOverlay()
  expect(errors).toEqual([])
})

test('system appearance updates without visiting settings', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' })
  await page.goto(seed)
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('.app-rail')).toHaveCSS('background-color', 'rgb(20, 20, 22)')
  await page.getByRole('button', { name: 'Open Week 03 — Aug 17-21, 2026', exact: true }).click()
  await expect(page.locator('.is-composer-overlay')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('dark-workspace.png') })
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('.app-rail')).toHaveCSS('background-color', 'rgb(242, 242, 244)')
})

test('composer stays centered between the navigation and materials rails', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto(seed)
  const composer = page.locator('.composer-shell')
  await expect(composer).toBeVisible()
  await expect(page.locator('.artifact-drawer')).toBeVisible()
  await expect(page.locator('.artifact-drawer-handle')).toHaveCount(0)
  await expect(page.locator('.app-rail-handle')).toHaveCount(0)
  await page.waitForTimeout(420)
  const width = async () => (await composer.boundingBox()).width
  const chatWidth = async () => (await page.locator('.workspace-chat').boundingBox()).width
  const initialWidth = await width()
  const initialChatWidth = await chatWidth()
  const context = page.locator(".artifact-rail section[aria-label='Context']")
  const topbarBox = await page.locator('.workspace-topbar').boundingBox()
  const contextStripBox = await page.locator('.chat-context-strip').boundingBox()
  await expect(context).toBeVisible()
  await expect(page.locator('.rail-connector-row')).toBeVisible()
  const contextBox = await context.boundingBox()
  const drawerBox = await page.locator('.artifact-drawer').boundingBox()
  const initialComposerBox = await composer.boundingBox()
  expect(Math.abs(drawerBox.y - (topbarBox.y + topbarBox.height))).toBeLessThanOrEqual(1)
  expect(drawerBox.y).toBeLessThanOrEqual(contextStripBox.y + 1)
  expect(contextBox.y + contextBox.height).toBeLessThanOrEqual(drawerBox.y + drawerBox.height + 1)
  expect(initialComposerBox.x + initialComposerBox.width).toBeLessThanOrEqual(drawerBox.x - 24)
  expect(Math.abs((initialComposerBox.x - (await page.locator('.workspace-chat').boundingBox()).x) - (drawerBox.x - (initialComposerBox.x + initialComposerBox.width)))).toBeLessThanOrEqual(2)
  expect(await page.locator('.artifact-drawer').evaluate((el) => getComputedStyle(el).position)).toBe('absolute')
  expect(Math.abs(initialWidth - (await width()))).toBeLessThanOrEqual(2)
  expect(Math.abs(initialChatWidth - (await chatWidth()))).toBeLessThanOrEqual(2)

  const closeRail = page.getByRole('button', { name: 'Close artifacts panel', exact: true })
  await expect(closeRail).toHaveAttribute('aria-expanded', 'true')
  await expect(closeRail).toHaveAttribute('aria-controls', 'artifacts-panel')
  await closeRail.click()
  await expect(page.locator('.artifact-drawer')).toHaveCount(0)
  const openRail = page.getByRole('button', { name: 'Open artifacts panel', exact: true })
  await expect(openRail).toBeVisible()
  await expect(openRail).toHaveAttribute('aria-expanded', 'false')
  expect(Math.abs(initialWidth - (await width()))).toBeLessThanOrEqual(2)
  await openRail.click()
  await expect(page.locator('.artifact-drawer')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close artifacts panel', exact: true })).toHaveAttribute('aria-expanded', 'true')
  expect(Math.abs(initialWidth - (await width()))).toBeLessThanOrEqual(2)

  await page.setViewportSize({ width: 1512, height: 900 })
  await page.waitForTimeout(220)
  const wideDrawer = await page.locator('.artifact-drawer').boundingBox()
  const wideTopbar = await page.locator('.workspace-topbar').boundingBox()
  const wideContextStrip = await page.locator('.chat-context-strip').boundingBox()
  const wideComposerBox = await composer.boundingBox()
  expect(Math.abs(wideDrawer.y - (wideTopbar.y + wideTopbar.height))).toBeLessThanOrEqual(1)
  expect(wideDrawer.y).toBeLessThanOrEqual(wideContextStrip.y + 1)
  expect(wideComposerBox.x + wideComposerBox.width).toBeLessThanOrEqual(wideDrawer.x - 24)
  const wideWidth = await width()
  await page.getByRole('button', { name: 'Close artifacts panel', exact: true }).click()
  await expect(page.locator('.artifact-drawer')).toHaveCount(0)
  expect(Math.abs(wideWidth - (await width()))).toBeLessThanOrEqual(2)
})

test('phone keeps its dedicated reader and fits the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto(seed)
  await expect(page.locator('#composer-input')).toBeVisible()
  await expect(page.locator('.is-composer-overlay')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Open lesson plan', exact: true }).click()
  await expect(page.locator('.is-mobile-reader')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
